name: Build and Deploy Sphinx Docs
 
on:

  push:

    branches:

      - main  # 你可以根据实际情况调整分支名称

  pull_request:
 
jobs:

  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 10
 
    steps:

    - name: Checkout to main branch

      uses: actions/checkout@v4.1.5
 
    - name: Set up Python

      uses: actions/setup-python@v5.1.0

      with:

        python-version: '3.10'  # 使用合适的 Python 版本
 
    - name: Install dependencies

      run: |

        python -m pip install --upgrade pip

        pip install sphinx
        pip install sphinx_rtd_theme
 
    - name: Build Sphinx documentation

      run: |
        pwd
        make html

      working-directory: ./docs
               
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
         publish_branch: gh_pages
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./docs/build/html
         force_orphan: true
              
