name: Build and Deploy Sphinx Docs
 
on:

  push:

    branches:

      - main  # 你可以根据实际情况调整分支名称

  pull_request:
 
jobs:

  build:

    runs-on: ubuntu-latest
    
    timeout-minutes: 10
 
    steps:

    - name: Checkout to main branch

      uses: actions/checkout@v4.1.5
 
    - name: Set up Python

      uses: actions/setup-python@v5.1.0

      with:

        python-version: '3.10'  # 使用合适的 Python 版本
 
    - name: Install dependencies

      run: |

        python -m pip install --upgrade pip

        pip install sphinx
        pip install sphinx_rtd_theme
 
    - name: Build Sphinx documentation

      run: |
        pwd
        make html

      working-directory: .
 
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4.0.5
      with:
        # GitHub token
        token:  ${{ secrets.GITHUB_TOKEN }}
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        preview: true
              
